"""empty message

Revision ID: 03b06d0df086
Revises: d9462c4100c2
Create Date: 2018-05-02 12:56:52.221445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b06d0df086'
down_revision = 'd9462c4100c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "This is for indentation"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('image_back', sa.VARCHAR(length=40), nullable=True))
    op.add_column('stock', sa.Column('image_front', sa.VARCHAR(length=40), nullable=True))
    op.add_column('stock', sa.Column('bought', sa.INTEGER(), nullable=True))
    op.drop_table('cart')
    # ### end Alembic commands ###
