"""hi

Revision ID: 05387871445d
Revises: 818678299dab
Create Date: 2018-04-19 14:45:55.147434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05387871445d'
down_revision = '818678299dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concerts', sa.Column('date_second', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concerts', 'date_second')
    # ### end Alembic commands ###
