"""change towncity to non-unique

Revision ID: 2337411c7c0b
Revises: 3a6c87ae5d3c
Create Date: 2018-04-16 09:54:48.642097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2337411c7c0b'
down_revision = '3a6c87ae5d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_towncity', table_name='user')
    op.create_index(op.f('ix_user_towncity'), 'user', ['towncity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_towncity'), table_name='user')
    op.create_index('ix_user_towncity', 'user', ['towncity'], unique=1)
    # ### end Alembic commands ###
