"""empty message

Revision ID: 3a6c87ae5d3c
Revises: dea7560eb1ab
Create Date: 2018-03-29 20:20:40.584309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6c87ae5d3c'
down_revision = 'dea7560eb1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address1', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('postcode', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('towncity', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_user_address1'), 'user', ['address1'], unique=True)
    op.create_index(op.f('ix_user_address2'), 'user', ['address2'], unique=True)
    op.create_index(op.f('ix_user_postcode'), 'user', ['postcode'], unique=True)
    op.create_index(op.f('ix_user_towncity'), 'user', ['towncity'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_towncity'), table_name='user')
    op.drop_index(op.f('ix_user_postcode'), table_name='user')
    op.drop_index(op.f('ix_user_address2'), table_name='user')
    op.drop_index(op.f('ix_user_address1'), table_name='user')
    op.drop_column('user', 'towncity')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    # ### end Alembic commands ###
