"""empty message

Revision ID: 818678299dab
Revises: 71cfdeff9084
Create Date: 2018-04-19 14:12:00.828149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818678299dab'
down_revision = '71cfdeff9084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_quant', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    op.drop_table('orders')
    # ### end Alembic commands ###
