"""empty message

Revision ID: a59d0987683f
Revises: 05387871445d
Create Date: 2018-04-25 12:50:31.093434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59d0987683f'
down_revision = '05387871445d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['itemid'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('concerts', 'date')
    op.drop_column('concerts', 'date_second')
    op.drop_column('store', 'stock')
    op.drop_column('store', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('size', sa.VARCHAR(length=40), nullable=True))
    op.add_column('store', sa.Column('stock', sa.INTEGER(), nullable=True))
    op.add_column('concerts', sa.Column('date_second', sa.DATETIME(), nullable=True))
    op.add_column('concerts', sa.Column('date', sa.VARCHAR(length=8), nullable=True))
    op.drop_table('stock')
    # ### end Alembic commands ###
