"""empty message

Revision ID: c52da2392892
Revises: f2155ace146e
Create Date: 2018-04-16 09:59:11.333359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52da2392892'
down_revision = 'f2155ace146e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('accesslevel', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_accesslevel'), 'user', ['accesslevel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accesslevel'), table_name='user')
    op.drop_column('user', 'accesslevel')
    # ### end Alembic commands ###
