"""empty message

Revision ID: d9462c4100c2
Revises: a59d0987683f
Create Date: 2018-04-26 11:30:07.516931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9462c4100c2'
down_revision = 'a59d0987683f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "but nothing happened"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'lktsbnean')
    op.add_column('concerts', sa.Column('date_second', sa.DATETIME(), nullable=True))
    op.drop_table('stock')
    op.drop_table('orders')
    op.drop_table('store')
    # ### end Alembic commands ###
