"""empty message

Revision ID: dea7560eb1ab
Revises: 82928dd6e2ab
Create Date: 2018-03-29 12:40:54.506722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea7560eb1ab'
down_revision = '82928dd6e2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('venue', sa.String(length=40), nullable=True),
    sa.Column('date', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
