"""change rest to non-unique

Revision ID: f2155ace146e
Revises: 2337411c7c0b
Create Date: 2018-04-16 09:56:05.975544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2155ace146e'
down_revision = '2337411c7c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_address1', table_name='user')
    op.create_index(op.f('ix_user_address1'), 'user', ['address1'], unique=False)
    op.drop_index('ix_user_address2', table_name='user')
    op.create_index(op.f('ix_user_address2'), 'user', ['address2'], unique=False)
    op.drop_index('ix_user_postcode', table_name='user')
    op.create_index(op.f('ix_user_postcode'), 'user', ['postcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_postcode'), table_name='user')
    op.create_index('ix_user_postcode', 'user', ['postcode'], unique=1)
    op.drop_index(op.f('ix_user_address2'), table_name='user')
    op.create_index('ix_user_address2', 'user', ['address2'], unique=1)
    op.drop_index(op.f('ix_user_address1'), table_name='user')
    op.create_index('ix_user_address1', 'user', ['address1'], unique=1)
    # ### end Alembic commands ###
